# Coop

restaurants:
  Aarau: '2042'
  Altdorf: '2139'
  Baden: '2524'
  Egerkingen: '2546'
  Emmenbrücke: '2135'
  Frick: '2047'
  Herzogenbuchsee: '2095'
  Langenthal: '2093'
  Lenzburg: '2037'
  Luzern: '2529'
  Möhlin: '2054'
  Olten: '2092'
  Sarnen: '2138'
  Stans: '2131'
  Wettingen: '2884'
  Zofingen: '2097'
