# Coop

restaurants:
  Aarau: '2042'
  Aarau Telli: '2039'
  Aarberg: '4698'
  Aclens Restaurant personnel: '3364'
  Affoltern am Albis: '2090'
  Allaman K.: '2348'
  Allschwil Letten: '4149'
  Altdorf: '2139'
  Amriswil Bistro: '2158'
  Appenzell Bistro: '2153'
  Arbon Novaseta: '2148'
  Au Centre Take it: '5300'
  Baar Delfin: '2133'
  Baar Gotthard: '2317'
  Bachenbülach: '2570'
  Baden: '2524'
  Basel Am Marktplatz: '2499'
  Basel City Pfauen Take it: '5301'
  Basel Europe Ca'Puccini: '4156'
  Basel Gundeli: '2048'
  Basel Pfauen: '2043'
  Basel Südpark Take it: '4288'
  Basel Volta Zentrum: '4150'
  Bassecourt: '2350'
  Bellinzona Centro: '2059'
  Belp: '2409'
  Bern Bethlehem: '2070'
  Bern Breitenrain: '2071'
  Bern Bümpliz: '2226'
  Bern Ryfflihof: '2069'
  Bern Ryfflihof Take it: '5302'
  Bern Wankdorf Center: '2914'
  Biberist: '2377'
  Biel Bahnhof: '2062'
  Biel Boujean: '4093'
  Biel Nidaugasse: '2066'
  Biel Nidaugasse Take it: '5312'
  Bottmingen Bistro: '2389'
  Bubendorf: '2055'
  Bulle Le Caro: '2473'
  Burgdorf Schützenmatte: '2544'
  Canobbio Ipermercato Resega: '4050'
  Carouge La Praille: '4070'
  Chur Quader: '2367'
  Chur West Restaurant: '4461'
  City St. Annahof Take it: '2162'
  Collombey: '2470'
  Conthey Bassin: '4057'
  Coop Personal Restaurant: '3709'
  Crissier: '2264'
  Crissier CremAmore: '4046'
  Davos: '2150'
  Dielsdorf: '2085'
  Dietikon Silbern: '2829'
  Dietlikon Center: '4055'
  Ecublens: '2123'
  Egerkingen Gäupark: '2546'
  Egerkingen Gäupark: '2901'
  Emmenbrücke: '2135'
  Engelberg: '2137'
  Eyholz Center: '4047'
  Feldmeilen Ca'Puccini: '4502'
  Feuerthalen Rhymarkt: '2146'
  Frauenfeld Schlosspark: '2144'
  Frenkendorf Bistro: '2390'
  Fribourg: '3743'
  Frick: '2047'
  Genève Eaux-Vives: '2110'
  Genève Fusterie: '2113'
  Genève Montbrillant: '2114'
  Genève Servette: '2107'
  Gossau SG: '2147'
  Granges-Paccot: '2563'
  Grenchen: '2406'
  Gstaad: '2080'
  Gümligen Zentrum: '3316'
  Heerbrugg: '2145'
  Heimberg Center: '4512'
  Herzogenbuchsee: '2095'
  Hinwil Center Restaurant: '4054'
  Ilanz Bistro: '2300'
  Interlaken Ost: '2079'
  Ittigen: '2077'
  Jona Eisenhof: '2254'
  Kaiseraugst: '4937'
  Kirchberg: '2068'
  Kreuzlingen Ca'Puccini: '4270'
  Kreuzlingen Karussell: '2143'
  Kriens Pilatusmarkt: '2847'
  Kriens Schappe Bistro: '2257'
  Köniz Stapfenmärit: '2074'
  La Chaux-de-Fonds Entilles: '2467'
  Landquart: '2155'
  Langenthal Tell: '2093'
  Langnau: '3687'
  Langnau Ca'Puccini: '4177'
  Lausanne Au Centre: '2118'
  Lausanne Saint-François: '2542'
  Lenzburg: '2037'
  Liestal Stabhof: '2044'
  Lugano: '2649'
  Lyss Stigli: '3794'
  Löwencenter LU: '2130'
  Martigny Cristal: '2428'
  Matran: '3711'
  Matran Ca'Puccini: '3763'
  Mels Pizolcenter: '2370'
  Montagny-près-Yverdon: '2666'
  Morges Charpentiers: '2124'
  Moudon Bistro: '3707'
  Muri AG: '3341'
  Möhlin: '2054'
  Münchenbuchsee: '2065'
  Münchenstein Garten Take it: '5305'
  Münchenstein Gartenstadt: '2045'
  Netstal Wiggispark: '2089'
  Neuchâtel: '2634'
  Neuchâtel Maladière: '3262'
  Neuchâtel Maladière Ca'Pucci: '3747'
  Oberwil: '2057'
  Oberwil Mühlematt: '4469'
  Olten: '2092'
  Orbe: '2126'
  Oron-La-Ville: '2101'
  Ostermundigen Bahnhof: '2076'
  Payerne Bistro: '2345'
  Porrentruy: '2106'
  Pratteln Bahnhof: '2050'
  Prilly Centre: '2121'
  Reinach AG: '2038'
  Reinach BL: '2056'
  Rheinfelden: '2046'
  Rickenbach: '2554'
  Romanshorn: '2156'
  Rorschach: '2152'
  Saignelégier Bistro: '4018'
  Sarnen: '2138'
  Schaffhausen: '2599'
  Schafisheim: '3702'
  Schenkon: '2575'
  Schlieren Lilien: '2088'
  Schwarzenburg: '2073'
  Seewen Markt: '2461'
  Serfontana: '2058'
  Sierre: '3580'
  Signy: '2115'
  Sion: '2098'
  St. Gallen Gallusmarkt: '2141'
  St. Moritz Bellevue Bistro: '2383'
  Stans: '2131'
  Tenero: '2874'
  Tenero CremAmore: '3559'
  Thalwil: '4457'
  Thun City Kyburg Take it: '2161'
  Thun Kyburg: '2078'
  Thun Strättligen Markt: '2866'
  Unterentfelden Ca'Puccini: '3845'
  Uznach Take it: '3776'
  Uzwil: '2149'
  Vernier: '4053'
  Vich: '2568'
  Villars-sur-Glâne: '4535'
  Volketswil Volkiland Bistro: '5306'
  Volketswil Volkiland Take it: '2481'
  Volkiland: '4902'
  Wattwil Bistro: '2157'
  Weinfelden Thurmarkt Rest.: '4583'
  Wettingen Tägipark: '2884'
  Wil Stadtmarkt: '2454'
  Willisau: '2258'
  Winterthur City: '4948'
  Winterthur Grüzemarkt: '2142'
  Winterthur Lokwerk: '4221'
  Winterthur Stadtgarten: '2140'
  Winterthur Stadtgarten Take : '4814'
  Wohlen Bistro: '2041'
  Worb: '2060'
  Würenlingen Aarepark: '3555'
  Yverdon Bel-Air: '2122'
  Zofingen: '2097'
  Zollikofen: '2067'
  Zuchwil Bistro: '2094'
  Zug: '2532'
  Zug Neustadt: '2136'
  Zürich A-Park Ca'Puccini: '4103'
  Zürich Bellevue: '2625'
  Zürich Eleven: '5080'
  Zürich Letzipark CremAmore: '4013'
  Zürich Letzipark Take it: '2167'
  Zürich St. Annahof: '2083'
  Zürich Wiedikon: '2084'

