# Coop

restaurants:
  Aarau: '2042'
  Affoltern am Albis: '2090'
  Apenzell Bistro: '2153'
  Allschwil: '4149'
  Allaman: '2348'
  Altdorf: '2139'
  Arbon: '2148'
  Baden: '2524'
  Baar Gotthard: '2317'
  Baar Delfin: '2133'
  Bachenbülach: '2570'
  Basel Am Marktplatz: '2499'
  Basel Pfauen: '2043'
  Basel Volta Zentrum: '4150'
  Basel Gundeli: '2048'
  Bassecourt: '2350'
  Belp: '2409'
  Bellinzona: '2059'
  Bern Ryfflihof: '2069'
  Bern Breitenrain: '2071'
  Bern Wankdorf Center: '2914'
  Burgdorf: '2544'
  Bulle Le Caro: '2473'
  Carouge: '4070'
  Canobbio: '4050'
  Chur Quader: '2367'
  Chur West: '4461'
  Conthey: '4057'
  Collombey: '2470'
  Crissier: '2264'
  Davos: '2150'
  Dietikon Silbern: '2829'
  Dielsdorf: '2085'
  Ecublens: '2123'
  Egerkingen: '2546'
  Emmenbrücke: '2135'
  Engelberg: '2137'
  Eyholz Center: '4047'
  Fribourg: '3743'
  Frauenfeld Schlosspark: '2144'
  Frick: '2047'
  Genève Fusterie: '2113'
  Genève Servette: '2107'
  Genève Eaux-Vives: '2110'
  Genève Montbrillant: '2114'
  Gossau SG: '2147'
  Grenchen: '2406'
  Granges-Paccot: '2563'
  Heimberg: '4512'
  Herzogenbuchsee: '2095'
  Heerbrugg: '2145'
  Hinwil Center: '4054'
  Interlaken: '2079'
  Ittigen: '2077'
  Jona Eisenhof: '2254'
  Kaiseraugst: '4937'
  Kirchberg: '2068'
  Kreuzlingen: '2143'
  Kriens Pilatusmarkt: '2847'
  Köniz: '2074'
  Langenthal: '2093'
  Landquart: '2155'
  Langnau: '3687'
  La Tour-de-Peilz: '2125'
  La Chaux-de-Fonds: '2467'
  Lenzburg: '2037'  
  Liestal: '2044'
  Lausanne Saint-François: '2542'
  Lausanne Au Centre: '2118'
  Luzern: '2529'
  Luzern Löwencenter: '2130'
  Lugano: '2649'
  Matran: '3711'
  Martigny: '2428'
  Mels Pizolcenter: '2370'
  Muri AG: '3341'
  Morges: '2124'
  Moudon Bistro: '3707'
  Montagny-près-Yverdon: '2666'
  Möhlin: '2054'
  Neuchâtel: '2634'
  Neuchâtel Maladière: '3262'
  Netstal: '2089'
  Oberwil: '2057'
  Oberwil Mühlematt: '4469'
  Olten: '2092'
  Onex: '2108'
  Oron-La-Ville: '2101'
  Orbe: '2126'
  Ostermundigen: '2076'
  Payerne Bistro: '2345'
  Pratteln: '2050'
  Prilly: '2121'
  Porrentruy: '2106'
  Reinach: '2038'
  Rheinfelden: '2046'
  Rorschach: '2152'
  Romanshorn: '2156'
  Rickenbach: '2554'
  Sarnen: '2138'
  Seewen Markt: '2461'
  Serfontana: '2058'
  Stans: '2131'
  St. Gallen: '2141'
  St.Moritz Bistro: '2383'
  Schenkon: '2575'
  Schwarzenburg: '2073' 
  Schönbühl: '4841'
  Schaffhausen: '2599'
  Schlieren Lilien: '2088'
  Signy: '2115'
  Sion: '2098'
  Sierre: '3580'
  Tenero: '2874'
  Thalwil: '4457'
  Thun Strättligen Markt: '2866'
  Thun Kyburg: '2078'
  Uzwil: '2149'
  Vernier: '4053'
  Vich: '2568'
  Villars-sur-Glâne: '4535'
  Wettingen: '2884'
  Weinfelden: '4583'
  Wil: '2454'
  Winterthur City: '4948'
  Winterthur Stadtgarten: '2140'
  Winterthur Grüzemarkt: '2142'
  Winterthur Lokwerk: '4221'
  Würenlingen: '3555'
  Willisau: '2258'
  Worb: '2060'
  Yverdon Bel-Air: '2122'
  Zofingen: '2097'
  Zug Neustadt: '2136'
  Zug: '2136'
  Zürich Bellevue: '2625'
  Zürich Eleven: '5080'
  Zürich St. Annahof: '2083'
  Zürich Wiedikon: '2084'
