# Coop

restaurants:
  Aarau: '2042'
  Baden: '2524'
  Egerkingen: '2546'
  Emmenbrücke: '2135'
  Frick: '2047'
  Lenzburg: '2037'
  Luzern: '2529'
  Olten: '2092'
  Wettingen: '2884'
  Zofingen: '2097'
