# Coop

restaurants:
  Aarau: '2042'
  Altdorf: '2139'
  Arbon: '2148'
  Baden: '2524'
  Bern Ryfflihof: '2069'
  Bern Breitenrain: '2071'
  Bern Wankdorf Center: '2914'
  Egerkingen: '2546'
  Emmenbrücke: '2135'
  Frick: '2047'
  Genève Fusterie: '2113'
  Genève Servette: '2107'
  Genève Eaux-Vives: '2110'
  Genève Montbrillant: '2114'
  Herzogenbuchsee: '2095'
  Kreuzlingen: '2143'
  Kriens Pilatusmarkt: '2847'
  Langenthal: '2093'
  Lenzburg: '2037'
  Luzern: '2529'
  Luzern Löwencenter: '2130'
  Möhlin: '2054'
  Olten: '2092'
  Ostermundigen: '2076'
  Rorschach: '2152'
  Romanshorn: '2156'
  Sarnen: '2138'
  Stans: '2131'
  Wettingen: '2884'
  Würenlingen: '3555'
  Zofingen: '2097'
  Zug Neustadt: '2136'
  Zug: '2136'
