# Coop

restaurants:
  Aarau: '2042'
  Affoltern am Albis: '2090'
  Allschwil: '4149'
  Altdorf: '2139'
  Arbon: '2148'
  Baden: '2524'
  Baar Gotthard: '2317'
  Baar Delfin: '2133'
  Basel Am Marktplatz: '2499'
  Basel Pfauen: '2043'
  Basel Volta Zentrum: '4150'
  Basel Gundeli: '2048'
  Bassecourt: '2350'
  Bern Ryfflihof: '2069'
  Bern Breitenrain: '2071'
  Bern Wankdorf Center: '2914'
  Egerkingen: '2546'
  Emmenbrücke: '2135'
  Frick: '2047'
  Genève Fusterie: '2113'
  Genève Servette: '2107'
  Genève Eaux-Vives: '2110'
  Genève Montbrillant: '2114'
  Grenchen: '2406'
  Herzogenbuchsee: '2095'
  Kaiseraugst: '4937'
  Kreuzlingen: '2143'
  Kriens Pilatusmarkt: '2847'
  Langenthal: '2093'
  Lenzburg: '2037'  
  Liestal: '2044'
  Luzern: '2529'
  Luzern Löwencenter: '2130'
  Muri AG: '3341'
  Möhlin: '2054'
  Oberwil: '2057'
  Oberwil Mühlematt: '4469'
  Olten: '2092'
  Ostermundigen: '2076'
  Pratteln: '2050'
  Porrentruy: '2106'
  Reinach: '2038'
  Rheinfelden: '2046'
  Rorschach: '2152'
  Romanshorn: '2156'
  Sarnen: '2138'
  Stans: '2131'
  Wettingen: '2884'
  Würenlingen: '3555'
  Zofingen: '2097'
  Zug Neustadt: '2136'
  Zug: '2136'
